apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  labels:
    app: dotnet
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dotnet
        octopusexport: OctopusExport
    spec:
      containers:
        - name: dotnet
          image: 'mcr.microsoft.com/dotnet/core/samples:aspnetapp'
          ports:
            - name: http
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-svc
  labels:
    name: dotnet-svc
    app: dotnet
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: dotnet

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dotnet
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dotnet.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: dotnet-svc
              servicePort: 80
